// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpwquyywknkvtckebnvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwd3F1eXl3a25rdnRja2VibnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzMxNTcsImV4cCI6MjA3NzE0OTE1N30.RWW4zqVpa7LQ4UgTp7w1uJhhuw-sVdR9Od3rZzP7Gvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});